env:
  node: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - warn
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
  keyword-spacing:
      - warn
      - before: true
