os:
  - linux
  - osx

language: node_js
node_js:
  - node
  - 8
  - 6

before_script:
  - export HAS_GTK3=FALSE
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source ./prepare-test-travis-linux.sh; fi

addons:
  apt:
    packages:
      - libgtk-3-dev
      - tango-icon-theme
